### ISSUE TITLE
How to guide

### ISSUE THREAD

**Issue by Dizzzlectic** [JulienCHATEAU/SWAutoPlay_GUI#1]
Hello!

First off, thank you so much for putting so much time and effort into SWAutoPlay and the GUI. Unfortunately, I'm not very familiar with Go or the environment. Would you be able to create a quick getting started guide, how you use SWAutoPlay together with the GUI?

Also, are you taking donations? I'd love to show my support.

**Comment by JulienCHATEAU** [comment]
After some tries and fixes, you can now find complete and correct READMEs about installation and usage !
If you're still interested you can give it a try and send me your feedback about it.
Thank you for your support !
